# Generated by Django 5.1.6 on 2025-03-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidades',
            field=models.ManyToManyField(related_name='medicos', to='sistema.especialidade'),
        ),
    ]
