# Generated by Django 5.1.6 on 2025-03-27 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_medico_especialidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidades',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidade_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sistema.especialidade'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(default=django.utils.timezone.now)),
                ('obeservacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('C', 'Cancelada'), ('M', 'Confirmada'), ('R', 'Realizada')], default='A', max_length=1)),
                ('medico_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.medico')),
                ('paciente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.paciente')),
            ],
        ),
    ]
